export const statusLabels: Record<string, string> = {
    pending: 'orders.status.pending',
    failed_01: 'orders.status.failed_01',
    confirmed: 'orders.status.confirmed',
    cancelled: 'orders.status.cancelled',
    postponed: 'orders.status.postponed',
    duplicate: 'orders.status.duplicate',
    failed_04: 'orders.status.failed_04',
    failed_05: 'orders.status.failed_05',
    wrong_number: 'orders.status.wrong_number',
    wrong_order: 'orders.status.wrong_order',
    message_sent: 'orders.status.message_sent',
    out_of_stock: 'orders.status.out_of_stock',
    processing: 'orders.status.processing',
    en_preparation: 'orders.status.en_preparation',
    ramasse: 'orders.status.ramasse',
    sorti_livraison: 'orders.status.sorti_livraison',
    delivered: 'orders.status.delivered',
    annule: 'orders.status.annule',
    tentative_01: 'orders.status.tentative_01',
    tentative_02: 'orders.status.tentative_02',
    tentative_03: 'orders.status.tentative_03',
    reporte_01: 'orders.status.reporte_01',
    client_absent: 'orders.status.client_absent',
    wrong_address: 'orders.status.wrong_address',
    retour_vendeur: 'orders.status.retour_vendeur',
    retourne_vendeur: 'orders.status.retourne_vendeur',
    paid: 'orders.status.paid',
    shipped: 'orders.status.shipped'
};

export const statusColors: Record<string, { bg: string, text: string, border: string, hover: string, active: string }> = {
    default: { bg: 'bg-slate-50', text: 'text-slate-600', border: 'border-slate-100', hover: 'hover:bg-slate-200', active: 'bg-indigo-600' },
    pending: { bg: 'bg-slate-50', text: 'text-slate-600', border: 'border-slate-200', hover: 'hover:bg-slate-100', active: 'bg-slate-600' },
    confirmed: { bg: 'bg-indigo-50', text: 'text-indigo-600', border: 'border-indigo-200', hover: 'hover:bg-indigo-100', active: 'bg-indigo-600' },
    delivered: { bg: 'bg-emerald-50', text: 'text-emerald-600', border: 'border-emerald-200', hover: 'hover:bg-emerald-100', active: 'bg-emerald-600' },
    cancelled: { bg: 'bg-rose-50', text: 'text-rose-600', border: 'border-rose-200', hover: 'hover:bg-rose-100', active: 'bg-rose-600' },
    postponed: { bg: 'bg-amber-50', text: 'text-amber-600', border: 'border-amber-200', hover: 'hover:bg-amber-100', active: 'bg-amber-600' },
    processing: { bg: 'bg-blue-50', text: 'text-blue-600', border: 'border-blue-200', hover: 'hover:bg-blue-100', active: 'bg-blue-600' },
    out_of_stock: { bg: 'bg-orange-50', text: 'text-orange-600', border: 'border-orange-200', hover: 'hover:bg-orange-100', active: 'bg-orange-600' },
    failed_01: { bg: 'bg-red-50', text: 'text-red-500', border: 'border-red-100', hover: 'hover:bg-red-100', active: 'bg-red-500' },
    failed_02: { bg: 'bg-red-50', text: 'text-red-500', border: 'border-red-100', hover: 'hover:bg-red-100', active: 'bg-red-500' },
    failed_03: { bg: 'bg-red-50', text: 'text-red-500', border: 'border-red-100', hover: 'hover:bg-red-100', active: 'bg-red-500' },
    retour_vendeur: { bg: 'bg-purple-50', text: 'text-purple-600', border: 'border-purple-200', hover: 'hover:bg-purple-100', active: 'bg-purple-600' },
    retourne_vendeur: { bg: 'bg-purple-50', text: 'text-purple-600', border: 'border-purple-200', hover: 'hover:bg-purple-100', active: 'bg-purple-600' },
};
